create table ad (
	ad_id INT PRIMARY KEY,
	show_salary BIT NOT NULL,
	minimum_license VARCHAR(50),
	minimum_experience INT,
	title VARCHAR(50) NOT NULL,
	time_added DATE NOT NULL,
	type VARCHAR(50),
	location VARCHAR(50),
	minimum_wage VARCHAR(50),
	maximum_wage VARCHAR(50),
	resume_date_expire DATE,
	description TEXT,
	contact_email VARCHAR(50) NOT NULL,
	intro_video_url VARCHAR(1000),
	company_id INT NOT NULL,
	FOREIGN KEY (company_id) REFERENCES company (company_id) ON DELETE CASCADE ON UPDATE CASCADE
);

insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (1, 1, 'XS', 5, 'Actuary', '7/1/2022', 'Open-architected', 'Malaysia', '$7416.18', '$47135.78', '12/27/2024', 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl', 'rcarress0@seesaa.net', 'http://meetup.com/libero/rutrum/ac.aspx', 13);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (2, 0, '3XL', 10, 'Community Outreach Specialist', '3/2/2022', 'content-based', 'Portugal', '$6001.75', '$47796.28', '1/16/2025', 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', 'sormiston1@skyrock.com', 'http://skyrock.com/vel.png', 12);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (3, 0, '2XL', 8, 'Pharmacist', '4/2/2022', 'Down-sized', 'Cameroon', '$13229.91', '$31095.89', '7/12/2024', 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', 'mdrowsfield2@yahoo.com', 'http://mail.ru/ante/ipsum/primis/in/faucibus/orci/luctus.xml', 7);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (4, 0, 'XL', 10, 'Assistant Professor', '5/12/2022', 'hub', 'Colombia', '$8127.71', '$17687.17', '12/26/2024', 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec', 'kmallatratt3@google.ru', 'http://illinois.edu/eget/semper/rutrum/nulla/nunc.js', 1);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (5, 1, 'M', 5, 'Budget/Accounting Analyst I', '3/15/2022', 'Advanced', 'Indonesia', '$7636.14', '$53168.51', '1/16/2024', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 'cflello4@dyndns.org', 'http://pcworld.com/mattis/nibh/ligula/nec/sem/duis/aliquam.xml', 16);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (6, 0, 'L', 3, 'Operator', '4/10/2022', 'moratorium', 'Brazil', '$14567.46', '$36458.22', '10/18/2024', 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', 'bgoodsir5@w3.org', 'https://apache.org/lobortis.xml', 18);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (7, 0, '3XL', 10, 'Administrative Assistant III', '1/13/2023', 'local area network', 'Germany', '$12210.94', '$58733.34', '10/22/2023', 'consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante', 'tslocom6@t-online.de', 'http://apache.org/gravida/nisi/at/nibh.jpg', 4);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (8, 1, 'XL', 5, 'Administrative Officer', '7/28/2022', 'pricing structure', 'Indonesia', '$8506.11', '$30929.38', '5/26/2023', 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer', 'asherbrooke7@census.gov', 'http://ucoz.ru/elementum/ligula.aspx', 4);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (9, 0, '2XL', 3, 'Engineer IV', '3/7/2022', 'Seamless', 'Indonesia', '$10116.67', '$52563.74', '12/1/2024', 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis', 'rdefrain8@gov.uk', 'https://deviantart.com/nascetur/ridiculus.jsp', 1);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (10, 0, 'M', 8, 'Staff Scientist', '8/24/2022', 'Organized', 'Yemen', '$8008.80', '$36195.85', '11/29/2023', 'penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 'oellerman9@arstechnica.com', 'http://utexas.edu/commodo/vulputate/justo/in/blandit.html', 11);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (11, 1, 'XS', 4, 'Environmental Tech', '7/3/2022', 'support', 'Russia', '$4336.23', '$31099.72', '1/17/2025', 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', 'dhasnipa@cnn.com', 'https://toplist.cz/rhoncus/aliquet/pulvinar.png', 10);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (12, 0, 'L', 7, 'VP Accounting', '8/21/2022', 'hierarchy', 'United States', '$10106.69', '$29019.97', '9/27/2023', 'in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti', 'rhansfordb@yolasite.com', 'https://hexun.com/sagittis/sapien/cum/sociis/natoque.xml', 14);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (13, 0, '2XL', 3, 'Marketing Assistant', '1/22/2022', 'analyzer', 'Czech Republic', '$8133.01', '$32635.01', '7/27/2024', 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis', 'hwormstonec@scribd.com', 'https://booking.com/platea/dictumst/aliquam.png', 16);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (14, 0, 'XL', 6, 'Analog Circuit Design manager', '12/26/2022', 'Persevering', 'Tajikistan', '$870.36', '$32429.68', '6/4/2024', 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 'bkirszd@businesswire.com', 'http://angelfire.com/nec/condimentum/neque/sapien/placerat/ante.json', 1);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (15, 0, '2XL', 7, 'Payment Adjustment Coordinator', '8/8/2022', 'upward-trending', 'Poland', '$8214.25', '$56089.96', '11/13/2024', 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', 'kvaile@devhub.com', 'http://t-online.de/libero/non/mattis/pulvinar/nulla/pede.html', 3);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (16, 1, 'XS', 4, 'Software Engineer II', '4/27/2022', 'time-frame', 'China', '$3243.45', '$45043.63', '6/26/2024', 'montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis', 'usollandf@51.la', 'http://cam.ac.uk/sem/fusce/consequat/nulla.jpg', 15);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (17, 1, 'XL', 10, 'Health Coach III', '1/9/2023', 'Grass-roots', 'Portugal', '$14544.00', '$50434.91', '1/20/2023', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', 'mpetracchig@cnbc.com', 'https://usgs.gov/quis/turpis.jpg', 14);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (18, 1, '3XL', 5, 'Geologist IV', '8/6/2022', 'leverage', 'Thailand', '$11209.89', '$28781.95', '7/3/2024', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 'coscolleeh@answers.com', 'http://so-net.ne.jp/pede/justo/lacinia/eget.aspx', 16);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (19, 0, 'M', 5, 'Physical Therapy Assistant', '7/28/2022', 'executive', 'Indonesia', '$7424.29', '$19393.40', '12/6/2024', 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non', 'sdousei@bigcartel.com', 'http://bing.com/non/mauris/morbi/non/lectus.js', 17);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (20, 0, 'S', 9, 'Marketing Manager', '1/5/2023', 'mobile', 'United States', '$2086.44', '$17683.48', '11/6/2023', 'felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat', 'mjaquestj@ebay.com', 'http://umn.edu/lorem/id/ligula/suspendisse/ornare/consequat.xml', 1);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (21, 0, 'S', 4, 'Staff Scientist', '1/4/2023', 'encompassing', 'China', '$12197.41', '$35739.19', '12/25/2023', 'nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient', 'awaterfieldk@omniture.com', 'https://go.com/ridiculus/mus/vivamus/vestibulum/sagittis/sapien/cum.html', 10);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (22, 1, 'XL', 8, 'Registered Nurse', '1/31/2022', 'secondary', 'Indonesia', '$8106.95', '$44151.09', '5/25/2023', 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', 'bpinckneyl@myspace.com', 'https://washingtonpost.com/dictumst/aliquam.xml', 17);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (23, 0, '2XL', 6, 'Help Desk Operator', '11/28/2022', 'superstructure', 'China', '$12087.84', '$40188.06', '11/13/2023', 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', 'wnewlingm@linkedin.com', 'https://sun.com/dolor/sit/amet/consectetuer/adipiscing/elit.xml', 12);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (24, 1, '3XL', 7, 'Technical Writer', '10/8/2022', 'Streamlined', 'Czech Republic', '$7472.44', '$47227.94', '3/16/2023', 'vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend', 'rsheen@examiner.com', 'http://shinystat.com/nec/condimentum/neque/sapien/placerat.js', 5);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (25, 1, 'XS', 6, 'Database Administrator I', '7/16/2022', 'policy', 'Zimbabwe', '$14757.69', '$50449.51', '9/3/2024', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', 'hchapeo@51.la', 'https://paginegialle.it/rutrum/at/lorem/integer/tincidunt.js', 1);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (26, 0, '2XL', 7, 'VP Accounting', '5/14/2022', 'cohesive', 'Sweden', '$8244.11', '$44806.50', '1/31/2023', 'in purus eu magna vulputate luctus cum sociis natoque penatibus et', 'jmayhowp@twitter.com', 'http://elegantthemes.com/parturient/montes.xml', 13);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (27, 0, 'M', 3, 'Safety Technician III', '4/1/2022', 'Diverse', 'Pakistan', '$9781.23', '$36956.50', '11/24/2024', 'lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat', 'ddunleyq@parallels.com', 'https://nsw.gov.au/nulla/ac/enim.json', 13);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (28, 0, 'XL', 7, 'Research Assistant III', '11/7/2022', 'global', 'Portugal', '$6214.42', '$57867.61', '6/5/2023', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus', 'osussemsr@mashable.com', 'https://fastcompany.com/montes/nascetur/ridiculus.html', 2);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (29, 1, '3XL', 8, 'Junior Executive', '4/16/2022', 'Implemented', 'Greenland', '$5639.51', '$57029.29', '7/31/2023', 'a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', 'smourants@goo.gl', 'http://scribd.com/nibh/ligula/nec.json', 17);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (30, 1, 'XS', 3, 'Dental Hygienist', '2/14/2022', 'systematic', 'Russia', '$1651.47', '$32878.71', '7/20/2023', 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam', 'dkonigt@mlb.com', 'http://yellowpages.com/nulla/eget/eros/elementum.png', 10);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (31, 0, '2XL', 3, 'Structural Analysis Engineer', '2/4/2022', 'impactful', 'Brazil', '$1683.27', '$45524.51', '11/24/2024', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam', 'cfortounu@prlog.org', 'https://ifeng.com/vestibulum/aliquet/ultrices/erat/tortor/sollicitudin.html', 11);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (32, 1, 'XL', 5, 'Sales Representative', '10/2/2022', 'Operative', 'Indonesia', '$12513.72', '$20564.23', '10/15/2024', 'orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 'gpowderv@umich.edu', 'https://drupal.org/vehicula.html', 13);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (33, 0, '2XL', 8, 'Administrative Officer', '8/27/2022', 'composite', 'Mongolia', '$10090.51', '$51114.98', '12/17/2023', 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh', 'ekilfedderw@weebly.com', 'https://ucsd.edu/a/pede/posuere/nonummy/integer.json', 6);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (34, 1, '2XL', 8, 'Nuclear Power Engineer', '1/6/2023', 'Ameliorated', 'Portugal', '$11105.50', '$28234.33', '8/4/2024', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', 'vdobbinx@dyndns.org', 'http://japanpost.jp/rhoncus.jpg', 13);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (35, 1, '3XL', 4, 'Graphic Designer', '2/8/2022', 'asymmetric', 'Brazil', '$3270.36', '$22410.10', '11/21/2024', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 'cnathany@vkontakte.ru', 'http://ucla.edu/nunc/vestibulum/ante/ipsum/primis/in/faucibus.jsp', 2);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (36, 0, 'L', 4, 'Senior Quality Engineer', '3/22/2022', 'internet solution', 'United States', '$5889.83', '$29493.43', '10/4/2024', 'vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus', 'meddyz@reference.com', 'https://ifeng.com/rhoncus/mauris/enim.jpg', 2);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (37, 1, '2XL', 6, 'Paralegal', '4/6/2022', 'Progressive', 'Peru', '$9787.99', '$59269.23', '10/23/2024', 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 'ktarver10@va.gov', 'http://hugedomains.com/varius/integer/ac/leo/pellentesque.jpg', 17);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (38, 0, 'S', 6, 'Senior Financial Analyst', '2/7/2022', 'strategy', 'Russia', '$2019.51', '$22034.69', '2/13/2024', 'nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in', 'ecrafter11@list-manage.com', 'http://com.com/mauris/viverra/diam/vitae/quam/suspendisse.json', 8);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (39, 0, '3XL', 3, 'Recruiter', '11/17/2022', 'artificial intelligence', 'Indonesia', '$2583.20', '$43224.51', '4/14/2023', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis', 'rwhitworth12@mediafire.com', 'https://yelp.com/in/libero/ut.aspx', 2);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (40, 1, 'XS', 5, 'Professor', '10/23/2022', 'concept', 'Poland', '$2535.29', '$58403.10', '3/14/2023', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien', 'vspellissy13@ycombinator.com', 'https://cdc.gov/risus/auctor/sed/tristique.jpg', 15);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (41, 1, 'XS', 4, 'Nurse', '4/6/2022', 'process improvement', 'Czech Republic', '$4243.75', '$48864.19', '8/6/2023', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 'hgamwell14@dailymail.co.uk', 'http://taobao.com/posuere/cubilia.png', 4);
insert into ad (ad_id, show_salary, minimum_license, minimum_experience, title, time_added, type, location, minimum_wage, maximum_wage, resume_date_expire, description, contact_email, intro_video_url, company_id) values (42, 1, '2XL', 3, 'Product Engineer', '9/3/2022', 'open system', 'China', '$5833.76', '$27244.95', '8/31/2024', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 'buttley15@dagondesign.com', 'http://amazon.com/eu/felis/fusce/posuere/felis.aspx', 10);
